# AP試験 問題バンク
# database.upsert_questions() に渡すリスト
# answer: "A" | "B" | "C" | "D"

QUESTIONS = [
    # ── 基礎理論 ───────────────────────────────────────────────
    {
        "category": "テクノロジ系", "subcategory": "基礎理論",
        "question": "2進数 1011 を10進数に変換した値はどれか。",
        "option_a": "9", "option_b": "10", "option_c": "11", "option_d": "12",
        "answer": "C",
        "explanation": "1×2³+0×2²+1×2¹+1×2⁰=8+0+2+1=11",
    },
    {
        "category": "テクノロジ系", "subcategory": "基礎理論",
        "question": "16進数 2A を10進数に変換した値はどれか。",
        "option_a": "32", "option_b": "40", "option_c": "42", "option_d": "52",
        "answer": "C",
        "explanation": "2×16+10=32+10=42",
    },
    {
        "category": "テクノロジ系", "subcategory": "基礎理論",
        "question": "1バイトで表現できる符号なし整数の最大値はどれか。",
        "option_a": "127", "option_b": "128", "option_c": "255", "option_d": "256",
        "answer": "C",
        "explanation": "2⁸-1=255",
    },
    {
        "category": "テクノロジ系", "subcategory": "基礎理論",
        "question": "論理演算 A AND (A OR B) を簡単にした結果はどれか。",
        "option_a": "A", "option_b": "B", "option_c": "A OR B", "option_d": "A AND B",
        "answer": "A",
        "explanation": "吸収則 A AND (A OR B) = A",
    },
    {
        "category": "テクノロジ系", "subcategory": "基礎理論",
        "question": "NOT(A AND B) を等価な式に変換したものはどれか（ド・モルガンの法則）。",
        "option_a": "(NOT A) AND (NOT B)",
        "option_b": "(NOT A) OR (NOT B)",
        "option_c": "A OR B",
        "option_d": "NOT A AND B",
        "answer": "B",
        "explanation": "NOT(A AND B)=(NOT A) OR (NOT B)",
    },
    {
        "category": "テクノロジ系", "subcategory": "基礎理論",
        "question": "浮動小数点数（IEEE 754）の構成要素として正しいものはどれか。",
        "option_a": "整数部・小数部",
        "option_b": "符号・指数部・仮数部",
        "option_c": "符号・整数部・小数部",
        "option_d": "ビット列のみ",
        "answer": "B",
        "explanation": "IEEE 754は符号(1bit)・指数部・仮数部で構成。広い範囲の数を表現できる",
    },
    {
        "category": "テクノロジ系", "subcategory": "基礎理論",
        "question": "ハミング符号の目的として正しいものはどれか。",
        "option_a": "データを圧縮する",
        "option_b": "1ビット誤りを検出・訂正する",
        "option_c": "データを暗号化する",
        "option_d": "2ビット以上の誤りを必ず訂正する",
        "answer": "B",
        "explanation": "ハミング符号は1ビット誤り訂正・2ビット誤り検出が可能な誤り訂正符号",
    },
    # ── アルゴリズムとプログラミング ──────────────────────────
    {
        "category": "テクノロジ系", "subcategory": "アルゴリズムとプログラミング",
        "question": "n個のデータに対するバブルソートの平均計算量はどれか。",
        "option_a": "O(1)", "option_b": "O(log n)", "option_c": "O(n)", "option_d": "O(n²)",
        "answer": "D",
        "explanation": "バブルソートは平均・最悪ともに O(n²)",
    },
    {
        "category": "テクノロジ系", "subcategory": "アルゴリズムとプログラミング",
        "question": "二分探索の前提条件として正しいものはどれか。",
        "option_a": "連結リストに格納されていること",
        "option_b": "昇順または降順にソートされていること",
        "option_c": "キーが付与されていること",
        "option_d": "件数が2のべき乗であること",
        "answer": "B",
        "explanation": "二分探索はソート済みが必須条件",
    },
    {
        "category": "テクノロジ系", "subcategory": "アルゴリズムとプログラミング",
        "question": "スタックで最後に追加した要素を取り出す操作を何というか。",
        "option_a": "enqueue", "option_b": "dequeue", "option_c": "push", "option_d": "pop",
        "answer": "D",
        "explanation": "スタックはLIFO。取り出しは pop、追加は push",
    },
    {
        "category": "テクノロジ系", "subcategory": "アルゴリズムとプログラミング",
        "question": "再帰アルゴリズムで必ず必要なものはどれか。",
        "option_a": "グローバル変数",
        "option_b": "終了条件（基底ケース）",
        "option_c": "配列",
        "option_d": "ループ",
        "answer": "B",
        "explanation": "終了条件がないと無限ループになる",
    },
    {
        "category": "テクノロジ系", "subcategory": "アルゴリズムとプログラミング",
        "question": "クイックソートの平均計算量はどれか。",
        "option_a": "O(n)", "option_b": "O(n log n)", "option_c": "O(n²)", "option_d": "O(log n)",
        "answer": "B",
        "explanation": "クイックソートの平均は O(n log n)。最悪は O(n²)",
    },
    {
        "category": "テクノロジ系", "subcategory": "アルゴリズムとプログラミング",
        "question": "キューで最初に追加した要素を取り出す操作を何というか。",
        "option_a": "push", "option_b": "pop", "option_c": "enqueue", "option_d": "dequeue",
        "answer": "D",
        "explanation": "キューはFIFO。取り出しは dequeue、追加は enqueue",
    },
    # ── コンピュータ構成要素 ──────────────────────────────────
    {
        "category": "テクノロジ系", "subcategory": "コンピュータ構成要素",
        "question": "CPUのパイプライン処理の目的はどれか。",
        "option_a": "メモリ容量を節約する",
        "option_b": "命令実行の並列化によりスループットを向上させる",
        "option_c": "消費電力を削減する",
        "option_d": "クロック周波数を上げる",
        "answer": "B",
        "explanation": "パイプラインは命令をフェッチ・デコード・実行などに分け並列処理しスループットを向上",
    },
    {
        "category": "テクノロジ系", "subcategory": "コンピュータ構成要素",
        "question": "キャッシュヒット率0.9、キャッシュアクセス10ns、主記憶100nsのとき実効アクセス時間はどれか。",
        "option_a": "10ns", "option_b": "19ns", "option_c": "55ns", "option_d": "100ns",
        "answer": "B",
        "explanation": "0.9×10+0.1×100=9+10=19ns",
    },
    {
        "category": "テクノロジ系", "subcategory": "コンピュータ構成要素",
        "question": "DRAMの特徴として正しいものはどれか。",
        "option_a": "リフレッシュ不要で高速",
        "option_b": "リフレッシュが必要で大容量・低コスト",
        "option_c": "SRAMよりアクセスが速い",
        "option_d": "キャッシュメモリに主に使われる",
        "answer": "B",
        "explanation": "DRAMはコンデンサで記憶するためリフレッシュが必要。大容量・低コストでメインメモリに使用",
    },
    {
        "category": "テクノロジ系", "subcategory": "コンピュータ構成要素",
        "question": "RISCの特徴として正しいものはどれか。",
        "option_a": "命令の種類が多く複雑な処理を1命令で実行",
        "option_b": "命令の種類が少なく固定長命令でパイプラインに向く",
        "option_c": "マイクロプログラム制御が主流",
        "option_d": "CISCよりクロック周波数が低い",
        "answer": "B",
        "explanation": "RISCは命令セットを絞り込み、固定長・高速パイプラインを実現",
    },
    {
        "category": "テクノロジ系", "subcategory": "コンピュータ構成要素",
        "question": "GPUがAI処理に適している理由として正しいものはどれか。",
        "option_a": "クロック周波数がCPUより高いため",
        "option_b": "並列演算コアが多数あり行列演算を高速処理できるため",
        "option_c": "消費電力が低いため",
        "option_d": "キャッシュメモリが大きいため",
        "answer": "B",
        "explanation": "GPUは数千のコアを持ちディープラーニングの行列・テンソル演算を大規模並列処理できる",
    },
    # ── システム構成要素 ──────────────────────────────────────
    {
        "category": "テクノロジ系", "subcategory": "システム構成要素",
        "question": "稼働率0.9のシステム2台を直列接続したときの稼働率はどれか。",
        "option_a": "0.81", "option_b": "0.90", "option_c": "0.99", "option_d": "0.95",
        "answer": "A",
        "explanation": "直列: 0.9×0.9=0.81",
    },
    {
        "category": "テクノロジ系", "subcategory": "システム構成要素",
        "question": "稼働率0.9のシステム2台を並列接続したときの稼働率はどれか。",
        "option_a": "0.81", "option_b": "0.90", "option_c": "0.99", "option_d": "0.95",
        "answer": "C",
        "explanation": "並列: 1-(1-0.9)²=1-0.01=0.99",
    },
    {
        "category": "テクノロジ系", "subcategory": "システム構成要素",
        "question": "MTBF=900時間、MTTR=100時間のとき稼働率はどれか。",
        "option_a": "0.90", "option_b": "0.91", "option_c": "0.99", "option_d": "0.95",
        "answer": "A",
        "explanation": "稼働率=MTBF/(MTBF+MTTR)=900/1000=0.9",
    },
    {
        "category": "テクノロジ系", "subcategory": "システム構成要素",
        "question": "ホットスタンバイの説明として正しいものはどれか。",
        "option_a": "待機系は電源断状態で待機",
        "option_b": "待機系も常時稼働して即時切替が可能",
        "option_c": "コールドスタンバイより費用が安い",
        "option_d": "性能差はコールドスタンバイと同じ",
        "answer": "B",
        "explanation": "ホットスタンバイは待機系も稼働中で即時切替可能。コールドは起動時間が必要",
    },
    # ── ソフトウェア ──────────────────────────────────────────
    {
        "category": "テクノロジ系", "subcategory": "ソフトウェア",
        "question": "プリエンプティブなマルチタスクOSの説明として正しいものはどれか。",
        "option_a": "タスクが自発的にCPUを解放するまで実行を続ける",
        "option_b": "OSが強制的にタスクを切り替えることができる",
        "option_c": "一度に1つのタスクしか実行できない",
        "option_d": "タスクの優先度は変更できない",
        "answer": "B",
        "explanation": "プリエンプティブは横取り可能の意。OSが強制的にCPUを切り替えられる",
    },
    {
        "category": "テクノロジ系", "subcategory": "ソフトウェア",
        "question": "仮想記憶のページング方式でページフォルト発生時にOSが行う処理はどれか。",
        "option_a": "プロセスを強制終了する",
        "option_b": "不足ページを補助記憶から主記憶に読み込む",
        "option_c": "ページサイズを拡大する",
        "option_d": "スワップ領域を削除する",
        "answer": "B",
        "explanation": "ページフォルトはアクセスしたページが主記憶にない状態。OSがディスクから読み込む",
    },
    {
        "category": "テクノロジ系", "subcategory": "ソフトウェア",
        "question": "スラッシングの説明として正しいものはどれか。",
        "option_a": "CPUがアイドル状態になること",
        "option_b": "ページ置換が頻発しCPU利用率が低下すること",
        "option_c": "メモリリークが発生すること",
        "option_d": "スワップ領域が不足すること",
        "answer": "B",
        "explanation": "スラッシングはページ置換処理に時間を取られCPU本来の処理効率が著しく低下する現象",
    },
    {
        "category": "テクノロジ系", "subcategory": "ソフトウェア",
        "question": "マイクロカーネルの特徴として正しいものはどれか。",
        "option_a": "OSの全機能をカーネルに含め性能を最大化する",
        "option_b": "最小限の機能のみカーネルに含め残りをユーザ空間で動作させる",
        "option_c": "仮想化技術をカーネルに組み込む",
        "option_d": "リアルタイム処理に特化した構造",
        "answer": "B",
        "explanation": "マイクロカーネルはIPC・基本スケジューリングのみをカーネル空間に置き、安定性・移植性を高める",
    },
    # ── ハードウェア ──────────────────────────────────────────
    {
        "category": "テクノロジ系", "subcategory": "ハードウェア",
        "question": "USB 3.0 の最大転送速度として最も近いものはどれか。",
        "option_a": "480 Mbps", "option_b": "5 Gbps", "option_c": "10 Gbps", "option_d": "40 Gbps",
        "answer": "B",
        "explanation": "USB 3.0 は SuperSpeed で最大 5 Gbps",
    },
    {
        "category": "テクノロジ系", "subcategory": "ハードウェア",
        "question": "SSDの特徴として正しいものはどれか。",
        "option_a": "磁気ディスクを使用するため振動に弱い",
        "option_b": "フラッシュメモリを使用し書き込み回数に上限がある",
        "option_c": "HDDより消費電力が高い",
        "option_d": "シーケンシャルアクセスのみ高速",
        "answer": "B",
        "explanation": "SSDはNANDフラッシュメモリを使用。書き込み寿命（TBW）に上限がある",
    },
    # ── マルチメディア ────────────────────────────────────────
    {
        "category": "テクノロジ系", "subcategory": "マルチメディア",
        "question": "JPEG圧縮方式の特徴として正しいものはどれか。",
        "option_a": "可逆圧縮で品質劣化がない",
        "option_b": "非可逆圧縮で圧縮率を上げると品質が低下する",
        "option_c": "アニメーション表現が得意",
        "option_d": "透過色をサポートしない",
        "answer": "B",
        "explanation": "JPEGはDCT変換を使った非可逆圧縮。写真に向くが品質と圧縮率はトレードオフ",
    },
    {
        "category": "テクノロジ系", "subcategory": "マルチメディア",
        "question": "44.1kHz・16bit・ステレオで1秒間の音声データサイズはどれか。",
        "option_a": "44.1 KB", "option_b": "88.2 KB", "option_c": "176.4 KB", "option_d": "352.8 KB",
        "answer": "C",
        "explanation": "44100×16bit×2ch=44100×2×2=176,400byte≒176.4KB",
    },
    {
        "category": "テクノロジ系", "subcategory": "マルチメディア",
        "question": "PNG形式の特徴として正しいものはどれか。",
        "option_a": "非可逆圧縮で写真に最適",
        "option_b": "可逆圧縮でアルファチャンネル（透過）をサポート",
        "option_c": "アニメーションに標準対応",
        "option_d": "CMYKカラーをサポート",
        "answer": "B",
        "explanation": "PNGは可逆圧縮でアルファチャンネルによる透過をサポート。ロゴや図形に適する",
    },
    # ── データベース ──────────────────────────────────────────
    {
        "category": "テクノロジ系", "subcategory": "データベース",
        "question": "関係データベースにおける「射影」の説明として正しいものはどれか。",
        "option_a": "条件に合う行を取り出す操作",
        "option_b": "指定した列を取り出す操作",
        "option_c": "2つの表を結合する操作",
        "option_d": "重複行を除去する操作",
        "answer": "B",
        "explanation": "射影（PROJECT）は列方向の抽出。行方向の抽出は選択（SELECT）",
    },
    {
        "category": "テクノロジ系", "subcategory": "データベース",
        "question": "第3正規形の条件として正しいものはどれか。",
        "option_a": "第1正規形かつ部分関数従属がない",
        "option_b": "第2正規形かつ推移的関数従属がない",
        "option_c": "第1正規形かつ多値従属がない",
        "option_d": "第2正規形かつ結合従属がない",
        "answer": "B",
        "explanation": "第3正規形：第2正規形を満たし、かつ推移的関数従属がないこと",
    },
    {
        "category": "テクノロジ系", "subcategory": "データベース",
        "question": "ACID特性の「I」が表すものはどれか。",
        "option_a": "Integrity（整合性）",
        "option_b": "Isolation（独立性）",
        "option_c": "Idempotency（冪等性）",
        "option_d": "Indexing（索引）",
        "answer": "B",
        "explanation": "ACID: Atomicity・Consistency・Isolation・Durability",
    },
    {
        "category": "テクノロジ系", "subcategory": "データベース",
        "question": "デッドロックの説明として正しいものはどれか。",
        "option_a": "1件のトランザクションが長時間ロックを保持すること",
        "option_b": "2件以上のトランザクションが互いのロック解放を待ち合い停止すること",
        "option_c": "インデックスがない検索が遅延すること",
        "option_d": "コミット前にデータが失われること",
        "answer": "B",
        "explanation": "デッドロックは循環待ちによりトランザクションが永久に進めなくなる状態",
    },
    {
        "category": "テクノロジ系", "subcategory": "データベース",
        "question": "SQLで重複行を除いて全行取得するキーワードはどれか。",
        "option_a": "UNIQUE", "option_b": "DISTINCT", "option_c": "EXCEPT", "option_d": "HAVING",
        "answer": "B",
        "explanation": "SELECT DISTINCT で重複を除去した結果セットを返す",
    },
    {
        "category": "テクノロジ系", "subcategory": "データベース",
        "question": "NoSQLデータベースの特徴として正しいものはどれか。",
        "option_a": "必ずACID特性を完全に満たす",
        "option_b": "スキーマレスで水平スケーリングが容易",
        "option_c": "SQLのみでクエリを発行する",
        "option_d": "トランザクション処理に特化している",
        "answer": "B",
        "explanation": "NoSQLはスキーマ柔軟性・水平スケール・高可用性を優先。CAP定理に基づくトレードオフがある",
    },
    # ── ネットワーク ──────────────────────────────────────────
    {
        "category": "テクノロジ系", "subcategory": "ネットワーク",
        "question": "OSI参照モデルのトランスポート層に相当するプロトコルはどれか。",
        "option_a": "IP", "option_b": "TCP", "option_c": "HTTP", "option_d": "Ethernet",
        "answer": "B",
        "explanation": "TCP/UDPはトランスポート層（第4層）。IPはネットワーク層（第3層）",
    },
    {
        "category": "テクノロジ系", "subcategory": "ネットワーク",
        "question": "サブネットマスク 255.255.255.0 のとき利用可能なホスト数はどれか。",
        "option_a": "254", "option_b": "255", "option_c": "256", "option_d": "253",
        "answer": "A",
        "explanation": "2⁸=256-ネットワークアドレス1-ブロードキャスト1=254",
    },
    {
        "category": "テクノロジ系", "subcategory": "ネットワーク",
        "question": "DNSの役割として正しいものはどれか。",
        "option_a": "MACアドレスからIPアドレスを解決する",
        "option_b": "ドメイン名からIPアドレスを解決する",
        "option_c": "IPアドレスからMACアドレスを解決する",
        "option_d": "ポート番号からサービス名を解決する",
        "answer": "B",
        "explanation": "DNS（Domain Name System）はドメイン名→IPアドレスの名前解決を行う",
    },
    {
        "category": "テクノロジ系", "subcategory": "ネットワーク",
        "question": "ARP（アドレス解決プロトコル）の役割として正しいものはどれか。",
        "option_a": "ドメイン名からIPアドレスを解決する",
        "option_b": "IPアドレスからMACアドレスを解決する",
        "option_c": "MACアドレスからIPアドレスを解決する",
        "option_d": "ポート番号とサービスを対応付ける",
        "answer": "B",
        "explanation": "ARPはIPアドレスをMACアドレスに解決するプロトコル",
    },
    {
        "category": "テクノロジ系", "subcategory": "ネットワーク",
        "question": "TLSが提供するセキュリティ機能に含まれないものはどれか。",
        "option_a": "通信内容の暗号化",
        "option_b": "サーバ認証",
        "option_c": "送信元IPアドレスの偽装防止",
        "option_d": "メッセージ完全性の確認",
        "answer": "C",
        "explanation": "TLSは暗号化・認証・完全性を提供するが、IPスプーフィング防止はIPsec等の役割",
    },
    {
        "category": "テクノロジ系", "subcategory": "ネットワーク",
        "question": "HTTPSで使用される標準ポート番号はどれか。",
        "option_a": "80", "option_b": "443", "option_c": "8080", "option_d": "8443",
        "answer": "B",
        "explanation": "HTTPSはポート443。HTTPはポート80",
    },
    {
        "category": "テクノロジ系", "subcategory": "ネットワーク",
        "question": "HTTP/2の特徴として正しいものはどれか。",
        "option_a": "テキスト形式のヘッダでデバッグが容易",
        "option_b": "1つのTCP接続で複数リクエストを多重化できる",
        "option_c": "UDPを使用する",
        "option_d": "HTTP/1.1より暗号化が強制される",
        "answer": "B",
        "explanation": "HTTP/2はバイナリフレーム化と多重化（ストリーム）により並列転送を実現",
    },
    # ── セキュリティ ──────────────────────────────────────────
    {
        "category": "テクノロジ系", "subcategory": "セキュリティ",
        "question": "SQLインジェクション攻撃への対策として最も効果的なものはどれか。",
        "option_a": "入力値の文字数を制限する",
        "option_b": "プリペアドステートメント（バインド変数）を使用する",
        "option_c": "エラーメッセージを詳細に表示する",
        "option_d": "パスワードをMD5でハッシュ化する",
        "answer": "B",
        "explanation": "プリペアドステートメントはSQLの構造と入力値を分離するためSQLインジェクションを根本的に防ぐ",
    },
    {
        "category": "テクノロジ系", "subcategory": "セキュリティ",
        "question": "XSS（クロスサイトスクリプティング）攻撃への対策として正しいものはどれか。",
        "option_a": "入力値のサニタイジングと出力時のHTMLエスケープ",
        "option_b": "SSL/TLSの使用",
        "option_c": "パスワードの強化",
        "option_d": "ファイアウォールの設置",
        "answer": "A",
        "explanation": "XSS対策はスクリプトを無害化するサニタイジングと出力時のエスケープ処理が基本",
    },
    {
        "category": "テクノロジ系", "subcategory": "セキュリティ",
        "question": "公開鍵暗号方式の説明として正しいものはどれか。",
        "option_a": "暗号化と復号に同一の鍵を使用する",
        "option_b": "公開鍵で暗号化し対応する秘密鍵で復号する",
        "option_c": "秘密鍵を通信相手と事前共有する",
        "option_d": "共通鍵方式より処理が高速",
        "answer": "B",
        "explanation": "公開鍵暗号は鍵ペアを使用。公開鍵で暗号化→秘密鍵で復号。鍵配送問題を解決",
    },
    {
        "category": "テクノロジ系", "subcategory": "セキュリティ",
        "question": "デジタル署名で送信者が行う操作はどれか。",
        "option_a": "ハッシュ値を送信者の公開鍵で暗号化する",
        "option_b": "ハッシュ値を送信者の秘密鍵で暗号化する",
        "option_c": "ハッシュ値を受信者の公開鍵で暗号化する",
        "option_d": "ハッシュ値を受信者の秘密鍵で暗号化する",
        "answer": "B",
        "explanation": "デジタル署名：送信者が自身の秘密鍵でハッシュを暗号化→受信者が公開鍵で検証",
    },
    {
        "category": "テクノロジ系", "subcategory": "セキュリティ",
        "question": "フィッシング攻撃の説明として正しいものはどれか。",
        "option_a": "大量パケットでサービスを妨害する攻撃",
        "option_b": "正規サイトに見せかけた偽サイトで認証情報を詐取する攻撃",
        "option_c": "バッファあふれを利用してコードを実行する攻撃",
        "option_d": "ネットワークを盗聴して情報を収集する攻撃",
        "answer": "B",
        "explanation": "フィッシングは偽サイト・メールでユーザを騙しID/パスワードを詐取するソーシャルエンジニアリング攻撃",
    },
    {
        "category": "テクノロジ系", "subcategory": "セキュリティ",
        "question": "ゼロデイ攻撃の説明として正しいものはどれか。",
        "option_a": "パッチ公開後に修正済み脆弱性を悪用する攻撃",
        "option_b": "脆弱性が公開される前（パッチ未提供の状態）に行われる攻撃",
        "option_c": "辞書を使ったパスワード解析攻撃",
        "option_d": "複数のシステムから一斉にアクセスするDDoS攻撃",
        "answer": "B",
        "explanation": "ゼロデイ攻撃はパッチが存在しない段階で脆弱性を突く攻撃。防御が困難",
    },
    {
        "category": "テクノロジ系", "subcategory": "セキュリティ",
        "question": "多要素認証（MFA）で正しい組み合わせはどれか。",
        "option_a": "知識要素（パスワード）と知識要素（秘密の質問）",
        "option_b": "知識要素（パスワード）と所持要素（スマートフォン）",
        "option_c": "所持要素（ICカード）と所持要素（OTP）",
        "option_d": "生体要素（指紋）と生体要素（顔認証）",
        "answer": "B",
        "explanation": "MFAは異なる種類の要素（知識・所持・生体）を組み合わせることでセキュリティを高める",
    },
    # ── システム開発技術 ──────────────────────────────────────
    {
        "category": "テクノロジ系", "subcategory": "システム開発技術",
        "question": "ウォーターフォールモデルの特徴として正しいものはどれか。",
        "option_a": "各フェーズを反復して開発を進める",
        "option_b": "各フェーズを順に進め前工程への戻りが少ない",
        "option_c": "短いサイクルで協調して開発する",
        "option_d": "最初に動作するプロトタイプを作成する",
        "answer": "B",
        "explanation": "ウォーターフォールは要件→設計→実装→テスト→運用の順に進む。前工程への戻りが困難",
    },
    {
        "category": "テクノロジ系", "subcategory": "システム開発技術",
        "question": "ブラックボックステストの説明として正しいものはどれか。",
        "option_a": "内部構造を理解してテストケースを設計する",
        "option_b": "仕様に基づき入出力だけを確認するテスト",
        "option_c": "カバレッジ100%を目指すテスト",
        "option_d": "ソースコードのバグを直接探すレビュー",
        "answer": "B",
        "explanation": "ブラックボックステストは内部実装を意識せず、仕様通りの入出力を検証する",
    },
    {
        "category": "テクノロジ系", "subcategory": "システム開発技術",
        "question": "回帰テストの目的として正しいものはどれか。",
        "option_a": "新機能が仕様通りに動作することを確認する",
        "option_b": "修正によって既存機能に不具合が生じていないことを確認する",
        "option_c": "負荷をかけてシステムの限界を調べる",
        "option_d": "セキュリティ脆弱性を発見する",
        "answer": "B",
        "explanation": "回帰テスト（リグレッションテスト）は変更後に既存機能の動作が壊れていないことを確認するテスト",
    },
    {
        "category": "テクノロジ系", "subcategory": "システム開発技術",
        "question": "テスト駆動開発（TDD）の手順として正しいものはどれか。",
        "option_a": "実装 → テスト作成 → リファクタリング",
        "option_b": "テスト作成（失敗）→ 実装（成功）→ リファクタリング",
        "option_c": "設計 → 実装 → テスト",
        "option_d": "テスト作成 → 設計 → 実装",
        "answer": "B",
        "explanation": "TDDのサイクル: Red（失敗テスト）→ Green（最小実装）→ Refactor",
    },
    {
        "category": "テクノロジ系", "subcategory": "システム開発技術",
        "question": "アジャイル開発の説明として正しいものはどれか。",
        "option_a": "全ての要件を事前に確定してから開発を開始する",
        "option_b": "短い反復サイクル（スプリント）で継続的に価値を届ける",
        "option_c": "ドキュメントを最重視する",
        "option_d": "変更要求を厳格に管理し変更を最小化する",
        "answer": "B",
        "explanation": "アジャイルは変化への対応を重視し、短いサイクルで動くソフトウェアを届け続ける手法",
    },
    # ── ソフトウェア開発管理技術 ──────────────────────────────
    {
        "category": "テクノロジ系", "subcategory": "ソフトウェア開発管理技術",
        "question": "ファンクションポイント法の説明として正しいものはどれか。",
        "option_a": "ソースコードの行数で規模を見積もる",
        "option_b": "機能の数と複雑さから規模を見積もる",
        "option_c": "類似プロジェクトの実績から見積もる",
        "option_d": "専門家の経験で見積もる",
        "answer": "B",
        "explanation": "FP法はユーザから見た機能（入力・出力・照会・内部論理ファイル・外部インタフェース）で規模を定量化",
    },
    {
        "category": "テクノロジ系", "subcategory": "ソフトウェア開発管理技術",
        "question": "EVMのSPI（スケジュール効率指数）が1未満を示すものはどれか。",
        "option_a": "予算内で完了している",
        "option_b": "予定より進捗が遅れている",
        "option_c": "予定より進捗が進んでいる",
        "option_d": "コストが計画通り",
        "answer": "B",
        "explanation": "SPI=EV/PV。SPI<1はスケジュール遅延を意味する",
    },
    # ── プロジェクトマネジメント ──────────────────────────────
    {
        "category": "マネジメント系", "subcategory": "プロジェクトマネジメント",
        "question": "クリティカルパスの説明として正しいものはどれか。",
        "option_a": "コストが最大の作業経路",
        "option_b": "プロジェクト全体の工期を決定する最長の作業経路",
        "option_c": "リスクが最大の作業経路",
        "option_d": "リソースを最も消費する作業経路",
        "answer": "B",
        "explanation": "クリティカルパスはフロートがゼロのタスクをつなぐ経路でプロジェクト最短完了期間を決定する",
    },
    {
        "category": "マネジメント系", "subcategory": "プロジェクトマネジメント",
        "question": "リスク対応戦略の「転嫁」の説明として正しいものはどれか。",
        "option_a": "リスクが発生しないよう原因を除去する",
        "option_b": "リスクの影響を第三者（保険等）に移転する",
        "option_c": "リスクを受け入れ影響が出たときに対処する",
        "option_d": "リスクの発生確率や影響を低減する",
        "answer": "B",
        "explanation": "転嫁（Transfer）は保険や契約によりリスクを第三者に移す戦略",
    },
    {
        "category": "マネジメント系", "subcategory": "プロジェクトマネジメント",
        "question": "WBS（作業分解構造）の説明として正しいものはどれか。",
        "option_a": "プロジェクトの作業を階層的に分解した図",
        "option_b": "プロジェクトメンバーの役割分担表",
        "option_c": "作業の順序と依存関係を示したネットワーク図",
        "option_d": "コストと進捗を管理するための図",
        "answer": "A",
        "explanation": "WBSはプロジェクトの成果物・作業を管理可能な単位に階層的に分解した構造図",
    },
    # ── サービスマネジメント ──────────────────────────────────
    {
        "category": "マネジメント系", "subcategory": "サービスマネジメント",
        "question": "ITILのインシデント管理の目的として正しいものはどれか。",
        "option_a": "インシデントの根本原因を特定し恒久対策を施す",
        "option_b": "サービスを可能な限り早く正常な状態に回復させる",
        "option_c": "変更要求を管理してサービスへの影響を最小化する",
        "option_d": "SLAの合意内容を管理する",
        "answer": "B",
        "explanation": "インシデント管理の目的はサービス影響の最小化と早期復旧。根本原因究明は問題管理の領域",
    },
    {
        "category": "マネジメント系", "subcategory": "サービスマネジメント",
        "question": "RTO（目標復旧時間）の説明として正しいものはどれか。",
        "option_a": "システム障害が発生してから復旧するまでの目標時間",
        "option_b": "復旧するデータの目標時点",
        "option_c": "年間稼働率の目標値",
        "option_d": "バックアップ取得の目標頻度",
        "answer": "A",
        "explanation": "RTO（Recovery Time Objective）は障害発生からサービス再開までの目標時間。RPOはデータの目標復旧時点",
    },
    {
        "category": "マネジメント系", "subcategory": "サービスマネジメント",
        "question": "SLA（サービスレベル協定）の説明として正しいものはどれか。",
        "option_a": "サービスの内部設計仕様書",
        "option_b": "サービス提供者と利用者間でサービス品質を定めた契約",
        "option_c": "障害対応の手順書",
        "option_d": "システムの性能テスト結果",
        "answer": "B",
        "explanation": "SLAはサービス提供者と顧客間で可用性・応答時間・サポート等の品質基準を合意した契約文書",
    },
    # ── システム戦略 ──────────────────────────────────────────
    {
        "category": "ストラテジ系", "subcategory": "システム戦略",
        "question": "BCP（事業継続計画）の説明として正しいものはどれか。",
        "option_a": "ITシステムのコスト削減計画",
        "option_b": "災害や事故発生時に事業を継続するための計画",
        "option_c": "新システム導入の移行計画",
        "option_d": "業務フローの改善計画",
        "answer": "B",
        "explanation": "BCPは大規模災害や事故時にも重要業務を継続・早期復旧するための体制・手順を定めた計画",
    },
    {
        "category": "ストラテジ系", "subcategory": "システム戦略",
        "question": "SaaSの説明として正しいものはどれか。",
        "option_a": "ハードウェアリソースをネット経由で提供するサービス",
        "option_b": "アプリケーションをネット経由で提供するサービス",
        "option_c": "OSや開発環境をネット経由で提供するサービス",
        "option_d": "データセンタの物理空間を提供するサービス",
        "answer": "B",
        "explanation": "SaaS（Software as a Service）はアプリをクラウドで提供。IaaSはインフラ、PaaSはプラットフォーム",
    },
    {
        "category": "ストラテジ系", "subcategory": "システム戦略",
        "question": "APIエコノミーの説明として正しいものはどれか。",
        "option_a": "APIの開発コストを削減する取り組み",
        "option_b": "APIを公開・連携することで新たなビジネス価値を生む仕組み",
        "option_c": "APIのセキュリティを強化する規格",
        "option_d": "マイクロサービスの設計手法",
        "answer": "B",
        "explanation": "APIエコノミーはAPIを外部公開し他社サービスと連携することで新ビジネスモデルを創出する概念",
    },
    # ── 経営戦略マネジメント ──────────────────────────────────
    {
        "category": "ストラテジ系", "subcategory": "経営戦略マネジメント",
        "question": "SWOT分析の「O」が表すものはどれか。",
        "option_a": "Objective（目標）",
        "option_b": "Opportunity（機会）",
        "option_c": "Output（成果）",
        "option_d": "Operation（業務）",
        "answer": "B",
        "explanation": "SWOT: Strength・Weakness・Opportunity・Threat",
    },
    {
        "category": "ストラテジ系", "subcategory": "経営戦略マネジメント",
        "question": "ポーターの競争戦略における「差別化戦略」の説明として正しいものはどれか。",
        "option_a": "コスト優位を徹底して価格競争で勝つ戦略",
        "option_b": "他社にない独自の価値を提供してプレミアム価格を得る戦略",
        "option_c": "特定の市場セグメントに絞り込む戦略",
        "option_d": "M&Aによって市場シェアを獲得する戦略",
        "answer": "B",
        "explanation": "差別化戦略は品質・ブランド・機能などで競合と差別化し、価格競争を避ける戦略",
    },
    {
        "category": "ストラテジ系", "subcategory": "経営戦略マネジメント",
        "question": "バランススコアカード（BSC）の4つの視点に含まれないものはどれか。",
        "option_a": "財務の視点",
        "option_b": "顧客の視点",
        "option_c": "競合の視点",
        "option_d": "学習と成長の視点",
        "answer": "C",
        "explanation": "BSCの4視点: 財務・顧客・内部業務プロセス・学習と成長。競合の視点は含まれない",
    },
    # ── 技術戦略マネジメント ──────────────────────────────────
    {
        "category": "ストラテジ系", "subcategory": "技術戦略マネジメント",
        "question": "ロードマップの説明として正しいものはどれか。",
        "option_a": "プロジェクトのWBS",
        "option_b": "技術・製品・市場の時間軸上の発展計画を示した図",
        "option_c": "リスク一覧表",
        "option_d": "コスト見積もり表",
        "answer": "B",
        "explanation": "技術ロードマップは技術の進化と市場ニーズを時間軸で整理し戦略的意思決定を支援するツール",
    },
    # ── ビジネスインダストリ ──────────────────────────────────
    {
        "category": "ストラテジ系", "subcategory": "ビジネスインダストリ",
        "question": "Fintech（フィンテック）の説明として正しいものはどれか。",
        "option_a": "製造業におけるIoT活用",
        "option_b": "金融サービスとITを融合させた革新的なサービス",
        "option_c": "政府の電子行政サービス",
        "option_d": "農業分野へのAI導入",
        "answer": "B",
        "explanation": "Fintech（Financial Technology）はAI・ブロックチェーン等を活用した決済・融資・資産管理等の革新的金融サービス",
    },
    {
        "category": "ストラテジ系", "subcategory": "ビジネスインダストリ",
        "question": "IoTシステムにおけるエッジコンピューティングの目的として正しいものはどれか。",
        "option_a": "クラウドへのデータ集約を増加させる",
        "option_b": "データ発生源近くで処理しレイテンシを低減する",
        "option_c": "サーバの台数を削減する",
        "option_d": "セキュリティを強化するためにデータを暗号化する",
        "answer": "B",
        "explanation": "エッジコンピューティングはデータ発生源近傍で処理することでクラウド転送量・遅延を減らす",
    },
    # ── 企業と法務 ────────────────────────────────────────────
    {
        "category": "ストラテジ系", "subcategory": "企業と法務",
        "question": "個人情報保護法で個人情報取扱事業者に求められる義務に含まれないものはどれか。",
        "option_a": "利用目的の通知・公表",
        "option_b": "第三者提供の原則的制限",
        "option_c": "個人情報の海外移転の禁止",
        "option_d": "安全管理措置の実施",
        "answer": "C",
        "explanation": "海外移転は本人同意等の条件を満たせば可能であり、一律禁止ではない",
    },
    {
        "category": "ストラテジ系", "subcategory": "企業と法務",
        "question": "著作権に関する説明として正しいものはどれか。",
        "option_a": "著作権の保護期間は著作者の死後25年",
        "option_b": "プログラムは著作権の保護対象外",
        "option_c": "著作権は著作物の創作時点で自動的に発生する",
        "option_d": "著作権は登録しなければ法的効力が生じない",
        "answer": "C",
        "explanation": "著作権は無方式主義。創作した瞬間に自動的に発生し登録は不要。保護期間は原則死後70年",
    },
    {
        "category": "ストラテジ系", "subcategory": "企業と法務",
        "question": "不正アクセス禁止法で禁止されている行為はどれか。",
        "option_a": "自分の権限でシステムにログインすること",
        "option_b": "他人のIDやパスワードを使ってシステムに不正アクセスすること",
        "option_c": "OSの脆弱性情報をベンダに報告すること",
        "option_d": "自社システムへ侵入テストを行うこと",
        "answer": "B",
        "explanation": "不正アクセス禁止法は正当なアクセス権限なくシステムにアクセスする行為を禁じる",
    },
    {
        "category": "ストラテジ系", "subcategory": "企業と法務",
        "question": "ROE（自己資本利益率）の計算式として正しいものはどれか。",
        "option_a": "当期純利益 ÷ 総資産 × 100",
        "option_b": "当期純利益 ÷ 自己資本 × 100",
        "option_c": "営業利益 ÷ 売上高 × 100",
        "option_d": "自己資本 ÷ 総資産 × 100",
        "answer": "B",
        "explanation": "ROE=当期純利益÷自己資本×100。株主から預かった資本の運用効率を示す",
    },
    # ── システム監査 ──────────────────────────────────────────
    {
        "category": "マネジメント系", "subcategory": "システム監査",
        "question": "システム監査の目的として正しいものはどれか。",
        "option_a": "システムのバグを全て修正すること",
        "option_b": "情報システムのリスクに対するコントロールが適切かを第三者が評価すること",
        "option_c": "システムの性能を向上させること",
        "option_d": "コストを削減すること",
        "answer": "B",
        "explanation": "システム監査はIT統制の有効性・効率性・信頼性を独立した第三者が評価する活動",
    },
    # ── システム企画 ──────────────────────────────────────────
    {
        "category": "ストラテジ系", "subcategory": "システム企画",
        "question": "RFP（提案依頼書）の説明として正しいものはどれか。",
        "option_a": "発注者が受注者に具体的な作業を指示する文書",
        "option_b": "発注者がベンダに対し提案を求める文書",
        "option_c": "ベンダが発注者に見積もりを提出する文書",
        "option_d": "システムの要件を詳細に記した仕様書",
        "answer": "B",
        "explanation": "RFP（Request For Proposal）は発注者が複数のベンダに提案・見積もりを依頼する文書",
    },
]
